### ISSUE TITLE
lab1-2 problem

### ISSUE THREAD

**Issue by LuminolT** [LuminolT/python-computation-lab-set#4]
When input value is `24:00:00`, error occured.

```
Please input a time, format: "HH:MM:SS"
24:00:00
Traceback (most recent call last):
  File "/home/luminol/GitHub/python-computation-lab-set/lab-1/sublab-2/timeoutput.py", line 9, in <module>
    main()
  File "/home/luminol/GitHub/python-computation-lab-set/lab-1/sublab-2/timeoutput.py", line 5, in main
    timestruct = datetime.datetime.strptime(timestring, "%H:%M:%S")
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00:00' does not match format '%H:%M:%S'
```

try to add error control part, or explain the code @Crazylian

**Comment by LuminolT** [comment]
treat it as an feat :-)
